### ISSUE TITLE
MSbuild script to build everything

### ISSUE THREAD

**Issue by znakeeye** [orx/orx#51]
When issuing the `setup` script, please create `build.xml` below in `vs2015`, `vs2017` and `vs2019` folders. That way, you can easily build **everything** with `msbuild`:

```
C:\Orx>msbuild build.xml
```

**build.xml**
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Target Name="Build">
    <MSBuild Projects="orx.sln" Properties="Configuration=Debug;Platform=Win32" />
    <MSBuild Projects="orx.sln" Properties="Configuration=Debug;Platform=x64" />
    <MSBuild Projects="orx.sln" Properties="Configuration=Release;Platform=Win32" />
    <MSBuild Projects="orx.sln" Properties="Configuration=Release;Platform=x64" />
    <MSBuild Projects="orx.sln" Properties="Configuration=Profile;Platform=Win32" />
    <MSBuild Projects="orx.sln" Properties="Configuration=Profile;Platform=x64" />
  
    <MSBuild Projects="orx.sln" Properties="Configuration=Core Debug;Platform=Win32" />
    <MSBuild Projects="orx.sln" Properties="Configuration=Core Debug;Platform=x64" />
    <MSBuild Projects="orx.sln" Properties="Configuration=Core Release;Platform=Win32" />
    <MSBuild Projects="orx.sln" Properties="Configuration=Core Release;Platform=x64" />
    <MSBuild Projects="orx.sln" Properties="Configuration=Core Profile;Platform=Win32" />
    <MSBuild Projects="orx.sln" Properties="Configuration=Core Profile;Platform=x64" />
  </Target>
</Project>
```

**Comment by iarwain** [comment]
Hi,

We could definitely look into modifying the version of premake orx is using in order to generate such file. However, I do not think it's going to be such a win in the end as one can only really have three "game" builds available at the same time:

- At the moment, 32bit and 64bit binaries are exclusive, you can't have both built versions at the same time.
- The Non-Core versions are only relevant when building the tools (orxCrypt & orxFontGen), and as such they're very rarely used.

In the end, compiling all versions of orx can done with three lines (that could be written in a batch file as well). Something like:
```
msbuild code/build/windows/<version>/orx.sln /p:Platform=<target> /p:Configuration=Release
msbuild code/build/windows/<version>/orx.sln /p:Platform=<target> /p:Configuration=Profile
msbuild code/build/windows/<version>/orx.sln /p:Platform=<target> /p:Configuration=Debug
```

**Comment by znakeeye** [comment]
I'd say it's a big win. You can install `msbuild` without `VS` being present.

**Comment by iarwain** [comment]
My point was more that the win is 1 line vs 3 lines to get all the configurations compiled.
